name: s3-contents-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - boto3
  - s3fs
  - requests
  - pytest
  - nose
  - mock
  - pip:
    - gcsfs
    - twine>=1.11.0
    - wheel
